{{- if and (not .Values.kubeconfigs.existingSecret) .Values.kubeconfigs.inline }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peevee.kubeconfigSecretName" . }}
  labels:
    {{- include "peevee.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $content := .Values.kubeconfigs.inline }}
  {{ $name }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
