{{- if and (not .Values.secrets.existingSecret) .Values.secrets.inline }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peevee.secretName" . }}
  labels:
    {{- include "peevee.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.inline }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
